### PR TITLE
[2311] Portugal 8.33

### PR DESCRIPTION
**Pull request by rffuret**
update to 8.33

### CODE REVIEW

**Comment by rffuret** [comment]
@jannikvogel please

**Review by jannikvogel — CHANGES_REQUESTED** [review]
i think Madeira secondary APP is still missing (line 2754). everything else lgtm :)

**Comment by rffuret** [comment]
That one is not changing

**Comment by jannikvogel** [comment]
> That one is not changing

roger, frequency in GNG appears to be wrongfully set to 8.33 in that case

**Review by jannikvogel — APPROVED** [review]

**Pull request merged**
